GET http://localhost:3000/fruit/1
###
POST http://localhost:3000/fruit
###
PUT http://localhost:3000/fruit
###
DELETE http://localhost:3000/fruit
###
GET http://localhost:3000/
###
POST http://localhost:3000/register
content-type: application/json

{
    "login":"tesfrft@t.fr",
    "mdp":"1ff23"
}
###
get http://localhost:3000/login
content-type: application/json

{
    "login":"tesfrft@t.fr",
    "mdp":"1ff23"
}
###